# Generated by Django 5.1.5 on 2025-01-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('subject', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('overall_score', models.FloatField(default=0)),
                ('Student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='student.teacher'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('assessment_marks', models.FloatField(default=0)),
                ('seminar_marks', models.FloatField(default=0)),
                ('assigment_marks', models.FloatField(default=0)),
                ('behaviour_marks', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.teacher')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
