# Generated by Django 5.1.5 on 2025-01-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
